apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: helmforge-production-claim2
  name: helmforge-production-claim2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
