apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-helmforge
  labels:
    app: helmforge
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helmforge
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: helmforge
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: helmforge
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: DOCKER_HOST
              value: "unix:///var/run/docker.sock"
            - name: HELM_HOME
              value: "/app/.helm"
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
